FROM mcr.microsoft.com/dotnet/aspnet:@Model.DotnetSdkVersion AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:@Model.DotnetSdkVersion AS build
WORKDIR /src
COPY . .
RUN dotnet restore
WORKDIR /src/src/@(Model.SolutionName).API
RUN dotnet build --no-restore -c Release -o /app/build

FROM build AS publish
RUN dotnet publish --no-restore -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "@(Model.SolutionName).API.dll"]